### ISSUE TITLE
Sugestão de função: "Meu espírito não está perdido"

### ISSUE THREAD

**Issue by VictorLopes** [ForceTower/Melon#54]
Permite o Unes mostrar as informações de contato de um professor como email, telefone, WhatsAPP, instagram, endereço, bairro, número da casa, estado civil, CPF, etc. (Ou só o email já tá bom mesmo).
Sugestão: Pode ser aberto um formulário no google docs onde os alunos podem contribuir com a informação.

**Comment by ForceTower** [comment]
aSUuHAUHsuhAHsu
https://uefsprofessores.firebaseapp.com/

Foi feito por Boa Morte!

**Comment by VictorLopes** [comment]
hahaha. Boa Morte Mito.
