### ISSUE TITLE
Tradução de strings!

### ISSUE THREAD

**Issue by ForceTower** [ForceTower/Melon#77]
O aplicativo atualmente suporta Português e Inglês, contudo existem algumas strings sem tradução!
Traduzir estas strings :)

**Comment by JoseDeFreitas** [comment]
Olá! I'm a native Spanish speaker and I would like to help to translate this. I don't know where can I find the English version? I'd prefer to use the English version to translate it into Spanish. Let me know if you actually want this contribution.
Apart from that, for a repository to be eligible for the Hacktoberfest event, the repository should have the "`hacktoberfest`" topic.

**Comment by ForceTower** [comment]
Sure! Spanish translations would be great!

The string files are named `strings.xml` and the english are usually under the `values-en` folder as it is the Android standard :)

https://github.com/ForceTower/Melon/blob/development/aeri/src/main/res/values-en-rUS/strings.xml
https://github.com/ForceTower/Melon/blob/development/app/src/main/res/values-en-rUS/strings.xml
https://github.com/ForceTower/Melon/blob/development/dashboard/src/main/res/values-en/strings.xml
https://github.com/ForceTower/Melon/blob/development/core/src/main/res/values-en/strings.xml
https://github.com/ForceTower/Melon/blob/development/event/src/main/res/values-en/strings.xml

Some strings are still not translated to english, so you probably wont find them in the english version! But I'd accept your contribution anyway :)

**Comment by ForceTower** [comment]
About the Hacktoberfest tag, don't worry, I'll tag your PR as `hacktoberfest-accepted` since this year rules are... insteresting to say the least :)

**Comment by JoseDeFreitas** [comment]
Perfect! I'll be working on it then. Should I create a `values-es` folder? And what about the `rUS`? Thank you.

**Comment by ForceTower** [comment]
Just `values-es` is fine

**Comment by MarcusAldrey** [comment]
Olá, farei traduções para o inglês

**Comment by ForceTower** [comment]
Closed at #78 and #79
